version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  credit-status-service:
    image: "node"
    #user: "node"
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./credit-status-service/:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3000:3000
    command: bash -c "npm install && npm run dev"
    environment:
      NODE_ENV: dev
      DB_HOST: mongo
      #MONGO_SRV: 'true'
      MONGO_USER: root
      MONGO_PASSWORD: example
      QUOTA_HOST: quota-service
      QUOTA_PORT: 3000
    depends_on:
      - "mongo"

  quota-service:
    image: "node"
    #user: "node"
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./quota-service/:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3001:3000
    command: bash -c "npm install && npm run dev"
    environment:
      NODE_ENV: dev
      DB_HOST: mongo
      #MONGO_SRV: 'true'
      MONGO_USER: root
      MONGO_PASSWORD: example
    depends_on:
      - "mongo"
